"""Version-aware normalisation: section tokens -> canonical offence IDs.  [owner: Gaurav — CORE NOVELTY, working]

The idea
--------
"IPC 302" in a 1995 judgment and "BNS 103" in a 2026 query are the same offence (punishment
for murder). Like stemming maps word forms to one term, we map section numbers from both codes
to one canonical offence ID, at index time AND query time:

    sec:ipc:302     -> sec:ipc:302, off:murder_bns103
    sec:bns:103(1)  -> sec:bns:103(1), off:murder_bns103
    sec:bns:302     -> sec:bns:302, off:uttering_words_etc_with_deliberate_intent   (the collision)

Offence ids are generated by ingest/parse_crosswalk.py from the BNS headings; `label()` gives
the readable name.

The original section token is kept (exact-section search still works); the offence token is
added after it. Split/merge mappings give weights below 1.0 (see `to_offences`).

Data files (see data/crosswalk/README.md for the formats)
    data/crosswalk/offence_ids.csv   offence_id, label, ipc_sections, bns_sections, keywords
    data/crosswalk/ipc_bns.csv       ipc_section, bns_section, relation, note

API: load, to_offences, offences_for, sections_of, equivalents, normalize_tokens, label.
"""

from __future__ import annotations

import csv
from collections import defaultdict
from dataclasses import dataclass, field

from kanoon_bridge.config import Config, load_config, project_path
from kanoon_bridge.text.tokenize import SECTION_PREFIX

OFFENCE_PREFIX = "off:"


@dataclass
class CrosswalkRow:
    ipc_section: str          # "" for a section new in BNS
    bns_section: str          # "" for a section dropped from BNS
    relation: str             # same | split | merge | new | dropped | modified
    note: str = ""


@dataclass
class VersionNormalizer:
    # section ref ("ipc:302") -> list of offence ids
    section_to_offences: dict[str, list[str]] = field(default_factory=lambda: defaultdict(list))
    # offence id -> {"label":..., "ipc": [...], "bns": [...], "keywords": [...]}
    offences: dict[str, dict] = field(default_factory=dict)
    crosswalk: list[CrosswalkRow] = field(default_factory=list)

    # ------------------------------------------------------------------ loading (working)
    @classmethod
    def load(cls, cfg: Config | None = None) -> "VersionNormalizer":
        cfg = cfg or load_config()
        norm = cls()
        off_path = project_path(cfg.paths.offence_ids)
        cw_path = project_path(cfg.paths.crosswalk)
        if not off_path.exists():
            raise FileNotFoundError(f"{off_path} missing")
        with open(off_path, encoding="utf-8") as f:
            for row in csv.DictReader(_skip_comments(f)):
                oid = row["offence_id"].strip().lower()
                ipc = _split(row.get("ipc_sections", ""))
                bns = _split(row.get("bns_sections", ""))
                norm.offences[oid] = {
                    "label": row.get("label", ""),
                    "ipc": ipc,
                    "bns": bns,
                    "keywords": _split(row.get("keywords", "")),
                }
                for s in ipc:
                    norm.section_to_offences[f"ipc:{s}"].append(oid)
                for s in bns:
                    norm.section_to_offences[f"bns:{s}"].append(oid)
        if cw_path.exists():
            with open(cw_path, encoding="utf-8") as f:
                for row in csv.DictReader(_skip_comments(f)):
                    norm.crosswalk.append(
                        CrosswalkRow(
                            ipc_section=row["ipc_section"].strip().lower(),
                            bns_section=row["bns_section"].strip().lower(),
                            relation=row["relation"].strip().lower(),
                            note=row.get("note", ""),
                        )
                    )
        return norm

    # ------------------------------------------------------------------ B builds these
    def to_offences(self, section_ref: str) -> list[tuple[str, float]]:
        """'ipc:302' -> [('off:murder_bns103', 1.0)].

        Exact sub-section first ('ipc:376(1)'), then the base section ('bns:103(2)' -> 'bns:103').
        A section in k offences gets weight 1/k each. Unknown code ('?:302') -> [] (collision.py
        resolves those first). Sections of other Acts (CrPC, Constitution, ...) -> [].
        """
        ref = section_ref.lower().removeprefix(SECTION_PREFIX)
        code, _, section = ref.partition(":")
        if code not in ("ipc", "bns") or not section:
            return []
        offs = self.section_to_offences.get(ref) or self.section_to_offences.get(f"{code}:{_base(section)}") or []
        offs = list(dict.fromkeys(offs))
        return [(o, 1.0 / len(offs)) for o in offs]

    def offences_for(self, section_ref: str) -> list[str]:
        """Just the offence ids of `to_offences`."""
        return [o for o, _ in self.to_offences(section_ref)]

    def sections_of(self, offence_id: str, code: str) -> list[str]:
        """Section refs of one code in an offence: ('off:murder_bns103', 'bns') -> ['bns:103']."""
        info = self.offences.get(offence_id)
        return [f"{code}:{s}" for s in info.get(code, [])] if info else []

    def equivalents(self, section_ref: str) -> list[str]:
        """Sections in the OTHER code with the same offence: 'ipc:302' -> ['bns:103'].

        Used by the demo ("IPC 302 = BNS 103") and by query expansion in query/analyzer.py.
        Sub-sections are reported at section level ('ipc:376(1)' -> 'bns:64').
        """
        ref = section_ref.lower().removeprefix(SECTION_PREFIX)
        code = ref.partition(":")[0]
        other = {"ipc": "bns", "bns": "ipc"}.get(code)
        if other is None:
            return []
        out: list[str] = []
        for off in self.offences_for(ref):
            for s in self.sections_of(off, other):
                base = f"{other}:{_base(s.partition(':')[2])}"
                if base not in out:
                    out.append(base)
        return out

    def normalize_tokens(self, tokens: list[str]) -> list[str]:
        """Insert 'off:<id>' tokens after every section token that maps to an offence.

        ['stab', 'sec:ipc:302'] -> ['stab', 'sec:ipc:302', 'off:murder_bns103']. The section token
        stays (exact-section search still works); positions shift by the added tokens, which is
        fine for proximity search at the granularity we use.
        """
        out: list[str] = []
        for tok in tokens:
            out.append(tok)
            if tok.startswith(SECTION_PREFIX):
                out.extend(self.offences_for(tok))
        return out

    def label(self, offence_id: str) -> str:
        """Human label for an offence id (for --debug and the demo)."""
        return self.offences.get(offence_id, {}).get("label", offence_id)


def _base(section: str) -> str:
    """'103(1)' -> '103'."""
    return section.split("(", 1)[0]


def _split(cell: str) -> list[str]:
    return [p.strip().lower() for p in (cell or "").split(";") if p.strip()]


def _skip_comments(lines):
    return (line for line in lines if not line.lstrip().startswith("#"))


__all__ = ["VersionNormalizer", "CrosswalkRow", "OFFENCE_PREFIX", "SECTION_PREFIX"]
